// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwdignhigsuopympzlxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZGlnbmhpZ3N1b3B5bXB6bHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTMwNjksImV4cCI6MjA2OTgyOTA2OX0.qgkh5IM1CYDdi5AFFaJ_CmQMYprQStLmnmtqlb8ku7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});